<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU040DialogContent" Id="{35b6e107-458a-4bdf-9564-bcdae88e1b0d}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU040DialogContent EXTENDS TcoCore.TcoInputDialogContentContainer
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
	{attribute addProperty Name "<#Recipe#>"}
	Recipe:STRING;
	{attribute addProperty Name "<#Qantity#>"}
	RequiredQuantity:INT;
	{attribute addProperty Name "<#Timeout#>"}
	Timeout:DATE_AND_TIME;
	{attribute addProperty Name "<#Exclude#>"}
	Exclude:BOOL;

END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CU040DialogContent">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>