<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU050ExampleCompositComponent" Id="{02a723f5-4be0-47f3-9ef7-13d5d0b6f3fe}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU050ExampleCompositComponent EXTENDS TcoCore.TcoComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CU050ExampleCompositComponent">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>