<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU040ManualTask" Id="{2203494c-e440-43e1-b2da-8abbda7d7511}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU040ManualTask EXTENDS TcoTaskedService IMPLEMENTS ICUTask
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Run();]]></ST>
    </Implementation>
    <Method Name="Main" Id="{6c71b746-70b9-4223-90f3-a350683250a5}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the sequener. Custom code needs to be placed here. The sequencer is executed by call of **Instance.Run()** method.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED Main : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Messenger.Notify('Running manual mode');
Station.Components.Group1.horizontalCylinder.Service();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnStart" Id="{2b52ea36-1277-4f28-968d-9c0eaaba55fd}">
      <Declaration><![CDATA[METHOD PROTECTED OnStart]]></Declaration>
      <Implementation>
        <ST><![CDATA[Station.AutomatTask.Restore();
Station.GroundTask.Restore();
Station.GroundTask.CancelGround();]]></ST>
      </Implementation>
    </Method>
    <Property Name="Station" Id="{068d8939-9783-4a05-8f45-03edef15128b}">
      <Declaration><![CDATA[PROPERTY Station : REFERENCE TO CU040]]></Declaration>
      <Get Name="Get" Id="{7e39b1e6-c366-4977-9f30-424ac7d23757}">
        <Declaration><![CDATA[VAR
    _station : POINTER TO CU040;
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IF __QUERYPOINTER(Parent, _station) THEN // Check if _Parent is Station001
    Station REF= _station^;              // If the check is successful dereference a pointer. simlar to THIS^ or SUPER^
END_IF]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="CU040ManualTask">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU040ManualTask.Main">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU040ManualTask.OnStart">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU040ManualTask.Station.Get">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>