<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU020ManualTask" Id="{1af38a75-db48-4ffa-915c-7a7d705d39bc}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU020ManualTask EXTENDS TcoTaskedService IMPLEMENTS ICUTask
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[Run();]]></ST>
    </Implementation>
    <Method Name="Main" Id="{91569f3f-a7a0-41fa-9d52-adc26d855830}">
      <Declaration><![CDATA[(*~
	<docu>
		<summary>
			Main method of the sequener. Custom code needs to be placed here. The sequencer is executed by call of **Instance.Run()** method.
			This method is abstract, and it must be overridden in derived block.
		</summary>
	</docu>
~*)
METHOD PROTECTED Main : BOOL
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Messenger.Notify('Running manual mode');
Station.Components.Group1.horizontalCylinder.Service();
]]></ST>
      </Implementation>
    </Method>
    <Method Name="OnStart" Id="{7e096d7f-2863-4523-8cef-604315d91c6c}">
      <Declaration><![CDATA[METHOD PROTECTED OnStart]]></Declaration>
      <Implementation>
        <ST><![CDATA[Station.AutomatTask.Restore();
Station.GroundTask.Restore();
Station.GroundTask.CancelGround();]]></ST>
      </Implementation>
    </Method>
    <Property Name="Station" Id="{4e553048-1c91-4ee4-a72c-26f122cabf45}">
      <Declaration><![CDATA[PROPERTY Station : REFERENCE TO CU020]]></Declaration>
      <Get Name="Get" Id="{67857616-7a80-4485-be51-2302cfd8df6b}">
        <Declaration><![CDATA[VAR
    _station : POINTER TO CU020;
END_VAR
]]></Declaration>
        <Implementation>
          <ST><![CDATA[IF __QUERYPOINTER(Parent, _station) THEN // Check if _Parent is Station001
    Station REF= _station^;              // If the check is successful dereference a pointer. simlar to THIS^ or SUPER^
END_IF]]></ST>
        </Implementation>
      </Get>
    </Property>
    <LineIds Name="CU020ManualTask">
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU020ManualTask.Main">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU020ManualTask.OnStart">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
    <LineIds Name="CU020ManualTask.Station.Get">
      <LineId Id="3" Count="1" />
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>