<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU010ExampleCompositComponent" Id="{0ed64ab4-648a-43c3-886f-aaf92674c0f7}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU010ExampleCompositComponent EXTENDS TcoCore.TcoComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CU010ExampleCompositComponent">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>