<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="CU030ExampleCompositComponent" Id="{2caa1da1-ca95-4d44-9c56-e0204ef86c62}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK CU030ExampleCompositComponent EXTENDS TcoCore.TcoComponent
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="CU030ExampleCompositComponent">
      <LineId Id="2" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>